// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtrGoYC26YhANBXKlM9evw63rieCGrlto',
    appId: '1:202126374933:web:20d05d61941c1a22e1761c',
    messagingSenderId: '202126374933',
    projectId: 'fir-flutter-codelab-d17e9',
    authDomain: 'fir-flutter-codelab-d17e9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d17e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnrBEzTgAg_4JaJ7e8kOdMQrQnB5MBRFw',
    appId: '1:202126374933:android:24a98b7a8dfc0432e1761c',
    messagingSenderId: '202126374933',
    projectId: 'fir-flutter-codelab-d17e9',
    storageBucket: 'fir-flutter-codelab-d17e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIt7Opf_Ic7cDtBAdASfye2rrYgRKev6M',
    appId: '1:202126374933:ios:26f9f0631a0fdf4ce1761c',
    messagingSenderId: '202126374933',
    projectId: 'fir-flutter-codelab-d17e9',
    storageBucket: 'fir-flutter-codelab-d17e9.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIt7Opf_Ic7cDtBAdASfye2rrYgRKev6M',
    appId: '1:202126374933:ios:26f9f0631a0fdf4ce1761c',
    messagingSenderId: '202126374933',
    projectId: 'fir-flutter-codelab-d17e9',
    storageBucket: 'fir-flutter-codelab-d17e9.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

}